// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://porrbburyucrddzxcaxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcnJiYnVyeXVjcmRkenhjYXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDExNTksImV4cCI6MjA2MDgxNzE1OX0.w7Z3FcmyCQuKTAOTZ1Z_-hlbRffR4jv74tlAiwy4c8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);